from app.schemas.auth import (
    AssignRoleIn,
    RefreshTokenIn,
    TokenPairOut,
    UserLoginIn,
    UserOut,
    UserRegisterIn,
)
from app.schemas.branch import BranchCreate, BranchOut
from app.schemas.catalog import BrandCreate, BrandOut, CategoryCreate, CategoryOut
from app.schemas.inventory import (
    InventoryCountCreateIn,
    InventoryCountLineOut,
    InventoryCountOut,
    InventoryCountPatchLinesIn,
)
from app.schemas.location import LocationCreate, LocationOut
from app.schemas.marketing import (
    AudienceSegmentCreate,
    AudienceSegmentOut,
    AudienceSegmentUpdate,
    CampaignCreate,
    CampaignOut,
    CampaignUpdate,
    ContentAssetCreate,
    ContentAssetOut,
    ContentAssetUpdate,
    MarketingChannelCreate,
    MarketingChannelOut,
    MarketingChannelUpdate,
    PromotionCreate,
    PromotionOut,
    PromotionUpdate,
)
from app.schemas.product import ProductCreate, ProductOut, ProductUpdate
from app.schemas.report import (
    PaginatedMeta,
    StockABCRow,
    StockTurnoverRow,
    StockValuationRow,
)
from app.schemas.sku import AddBarcodeIn, SKUCreate, SKUOut, SKUUpdate
from app.schemas.stock import (
    StockAdjustmentIn,
    StockBalanceOut,
    StockIssueIn,
    StockMoveOut,
    StockReceiptIn,
)
from app.schemas.transfer import (
    TransferCreateIn,
    TransferItemIn,
    TransferItemOut,
    TransferOut,
)

__all__ = [
    "AddBarcodeIn",
    "AssignRoleIn",
    "AudienceSegmentCreate",
    "AudienceSegmentOut",
    "AudienceSegmentUpdate",
    "BrandCreate",
    "BrandOut",
    "BranchCreate",
    "BranchOut",
    "CampaignCreate",
    "CampaignOut",
    "CampaignUpdate",
    "CategoryCreate",
    "CategoryOut",
    "ContentAssetCreate",
    "ContentAssetOut",
    "ContentAssetUpdate",
    "InventoryCountCreateIn",
    "InventoryCountLineOut",
    "InventoryCountOut",
    "InventoryCountPatchLinesIn",
    "LocationCreate",
    "LocationOut",
    "MarketingChannelCreate",
    "MarketingChannelOut",
    "MarketingChannelUpdate",
    "PaginatedMeta",
    "ProductCreate",
    "ProductOut",
    "ProductUpdate",
    "PromotionCreate",
    "PromotionOut",
    "PromotionUpdate",
    "RefreshTokenIn",
    "SKUUpdate",
    "SKUCreate",
    "SKUOut",
    "StockABCRow",
    "StockAdjustmentIn",
    "StockBalanceOut",
    "StockIssueIn",
    "StockMoveOut",
    "StockReceiptIn",
    "StockTurnoverRow",
    "StockValuationRow",
    "TokenPairOut",
    "TransferCreateIn",
    "TransferItemIn",
    "TransferItemOut",
    "TransferOut",
    "UserLoginIn",
    "UserOut",
    "UserRegisterIn",
]
