"""add transfers inventory auth reports hardening

Revision ID: 678cb1a6f4bf
Revises: edb3aaa8ba07
Create Date: 2026-02-16 10:10:08.953629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "678cb1a6f4bf"
down_revision: Union[str, Sequence[str], None] = "edb3aaa8ba07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("route", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "route", name="uq_idempotency_key_route"),
    )
    op.create_index(
        "ix_idempotency_created_at", "idempotency_keys", ["created_at"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=150), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=120), nullable=True),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("meta_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_resource",
        "audit_logs",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_user_created_at",
        "audit_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "role_id", "permission_id", name="uq_role_permissions_role_permission"
        ),
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_roles_user_role"),
    )
    op.create_table(
        "inventory_counts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN", "CLOSED", "POSTED", "CANCELLED", name="inventory_count_status"
            ),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_counts_status_started_at",
        "inventory_counts",
        ["status", "started_at"],
        unique=False,
    )
    op.create_table(
        "transfer_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_branch_id", sa.Integer(), nullable=False),
        sa.Column("from_location_id", sa.Integer(), nullable=False),
        sa.Column("to_branch_id", sa.Integer(), nullable=False),
        sa.Column("to_location_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "SHIPPED", "RECEIVED", "CANCELLED", name="transfer_status"
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["from_branch_id"], ["branches.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["from_location_id"], ["locations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["to_branch_id"], ["branches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["to_location_id"], ["locations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transfer_orders_status_created_at",
        "transfer_orders",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "inventory_count_lines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("count_id", sa.Integer(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("system_qty", sa.Integer(), nullable=False),
        sa.Column("counted_qty", sa.Integer(), nullable=True),
        sa.Column("diff_qty", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "posted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["count_id"], ["inventory_counts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "count_id", "sku_id", name="uq_inventory_count_line_count_sku"
        ),
    )
    op.create_table(
        "sku_barcodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("barcode", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("barcode", name="uq_sku_barcodes_barcode"),
    )
    op.create_table(
        "transfer_order_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transfer_id", sa.Integer(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sku_id"], ["skus.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["transfer_id"], ["transfer_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "transfer_id", "sku_id", name="uq_transfer_item_transfer_sku"
        ),
    )
    op.add_column("products", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("products", sa.Column("category_id", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("brand_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "products", "categories", ["category_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "products", "brands", ["brand_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("skus", sa.Column("name", sa.String(length=200), nullable=True))
    op.add_column("skus", sa.Column("attributes", sa.JSON(), nullable=True))
    op.add_column(
        "skus",
        sa.Column(
            "cost",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "skus",
        sa.Column(
            "price",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column("skus", sa.Column("tax_code", sa.String(length=50), nullable=True))
    op.add_column(
        "skus",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_skus_product_id", "skus", ["product_id"], unique=False)
    op.add_column(
        "stock_balances", sa.Column("location_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        op.f("uq_stock_balances_branch_sku"), "stock_balances", type_="unique"
    )
    op.create_index(
        "ix_stock_balances_lookup",
        "stock_balances",
        ["branch_id", "location_id", "sku_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_stock_balances_branch_sku_location",
        "stock_balances",
        ["branch_id", "sku_id", "location_id"],
    )
    op.create_index(
        "uq_stock_balances_branch_sku_null_location",
        "stock_balances",
        ["branch_id", "sku_id"],
        unique=True,
        postgresql_where=sa.text("location_id IS NULL"),
    )
    op.create_foreign_key(
        None, "stock_balances", "locations", ["location_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("stock_moves", sa.Column("transfer_id", sa.Integer(), nullable=True))
    op.add_column(
        "stock_moves", sa.Column("inventory_count_id", sa.Integer(), nullable=True)
    )
    op.add_column("stock_moves", sa.Column("created_by", sa.Integer(), nullable=True))
    op.create_index(
        "ix_stock_moves_branch_location_sku_created",
        "stock_moves",
        ["branch_id", "location_id", "sku_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_stock_moves_type_created",
        "stock_moves",
        ["move_type", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "stock_moves",
        "inventory_counts",
        ["inventory_count_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "stock_moves", "users", ["created_by"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None,
        "stock_moves",
        "transfer_orders",
        ["transfer_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stock_moves", type_="foreignkey")
    op.drop_constraint(None, "stock_moves", type_="foreignkey")
    op.drop_constraint(None, "stock_moves", type_="foreignkey")
    op.drop_index("ix_stock_moves_type_created", table_name="stock_moves")
    op.drop_index(
        "ix_stock_moves_branch_location_sku_created", table_name="stock_moves"
    )
    op.drop_column("stock_moves", "created_by")
    op.drop_column("stock_moves", "inventory_count_id")
    op.drop_column("stock_moves", "transfer_id")
    op.drop_constraint(None, "stock_balances", type_="foreignkey")
    op.drop_index(
        "uq_stock_balances_branch_sku_null_location",
        table_name="stock_balances",
        postgresql_where=sa.text("location_id IS NULL"),
    )
    op.drop_constraint(
        "uq_stock_balances_branch_sku_location", "stock_balances", type_="unique"
    )
    op.drop_index("ix_stock_balances_lookup", table_name="stock_balances")
    op.create_unique_constraint(
        op.f("uq_stock_balances_branch_sku"),
        "stock_balances",
        ["branch_id", "sku_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("stock_balances", "location_id")
    op.drop_index("ix_skus_product_id", table_name="skus")
    op.drop_column("skus", "created_at")
    op.drop_column("skus", "tax_code")
    op.drop_column("skus", "price")
    op.drop_column("skus", "cost")
    op.drop_column("skus", "attributes")
    op.drop_column("skus", "name")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "brand_id")
    op.drop_column("products", "category_id")
    op.drop_column("products", "description")
    op.drop_table("transfer_order_items")
    op.drop_table("sku_barcodes")
    op.drop_table("inventory_count_lines")
    op.drop_index("ix_transfer_orders_status_created_at", table_name="transfer_orders")
    op.drop_table("transfer_orders")
    op.drop_index(
        "ix_inventory_counts_status_started_at", table_name="inventory_counts"
    )
    op.drop_table("inventory_counts")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_index("ix_audit_logs_user_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_resource", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_index("ix_idempotency_created_at", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_table("categories")
    op.drop_table("brands")
    # ### end Alembic commands ###
